### ISSUE TITLE
defining self.maps in AcousticScene

### ISSUE THREAD

**Issue by JuanFMontesinos** [DavidDiazGuerra/icoDOA#3]
Hi again! :)

I was wondering how to define `self.maps` in the AcousticScene. It seems it enables a bunch of nice visualizations.
https://github.com/DavidDiazGuerra/icoDOA/blob/04d1a89594c78ae3cf42f07d94c3737bdc1f7c82/acousticTrackingDataset.py#L528-L559

Given how the code is done I assume you can append the maps at some stage to the acousticscene instance during inference. But It was a bit hard to track. Is there an straight foward way to do so?

Juan

**Comment by DavidDiazGuerra** [comment]
Hi Juan!

I know that part of the code wasn't very elegant 😅

All that code comes from the previous version of this research ([Cross3D](https://github.com/DavidDiazGuerra/Cross3D)) where I used equiangular maps and conventional 2D convolutions instead of the icosahedral maps and the icoCNNs. The `maps` field in `AcousticScene` was defined when calling `learner.predict_dataset` with the parameters `save_x=True` and `x_filed_name='maps'`. You can try to do the same in this repository by adding those parameters to this line:

https://github.com/DavidDiazGuerra/icoDOA/blob/04d1a89594c78ae3cf42f07d94c3737bdc1f7c82/1sourceTracking_icoCNN.py#L140

but, tbh, I'm not sure if that will work or if it will crash somehow. 

However, even if you're able to define the maps field, I'm afraid you won't be able to use those visualizations since those functions are based on the function [`plot_srp_map`](https://github.com/DavidDiazGuerra/icoDOA/blob/04d1a89594c78ae3cf42f07d94c3737bdc1f7c82/acousticTrackingDataset.py#L1126) which is not updated to work with icosahedral maps. If you want to visualize icosahedral maps I would suggest you use the [plotting functions](https://github.com/DavidDiazGuerra/icoCNN/blob/master/plots.md) included in the icoCNN package.

Another way of getting the SRP-PHAT maps is using the [`TrackingLearner.getNetworkInput_batch`](https://github.com/DavidDiazGuerra/icoDOA/blob/04d1a89594c78ae3cf42f07d94c3737bdc1f7c82/acousticTrackingLearners.py#L48-L54) function. After `test_dataset` (or `train_dataset`) and `learner` are defined as done in the main script, you can do something like this to get the icosahedral SRP-PHAT maps that are used as network input:

```
mic_signals, acoustic_scene = dataset_test[0]
ico_maps = learner.getNetworkInput_batch(mic_signals[np.newaxis, ...], [acoustic_scene])
```

Best regards,
David

**Comment by JuanFMontesinos** [comment]
I see, thanks!
I was mainly looking for a way to show compare the srp-phat maps heatmaps vs the icosaedral ones. 
![image](https://user-images.githubusercontent.com/32466310/227528774-3b82ecfe-7957-466c-9c2e-b39a076788a7.png)
Seems you make in both papers the projection to the same space 
![image](https://user-images.githubusercontent.com/32466310/227528879-15254d38-786f-45e6-8aa8-c23cedc98092.png)
That's enough :)
